# Generated by Django 4.2.6 on 2023-11-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/user_avatar_placeholder.jpeg', null=True, upload_to='avatars/'),
        ),
    ]
