# Generated by Django 4.2.6 on 2023-12-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_answerreaction_questionreaction_delete_answermanager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerreaction',
            name='type',
            field=models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='questionreaction',
            name='type',
            field=models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default=True, max_length=10),
        ),
    ]
